version: '3.1'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ../.env
    environment:
      - DB_URL=jdbc:postgresql://db:5432/restapi_cats
    expose:
      - '8080'
    ports:
      - '8080:8080'
    depends_on:
      - db
  db:
    image: 'postgres'
    container_name: db
    env_file: ../.env
    expose:
      - '5432'
